import 'dart:ui';

import '../bolan_theme.dart';

const carbonTheme = BolonTheme(
  name: 'carbon',
  displayName: 'Carbon',
  brightness: Brightness.dark,
  isBuiltIn: true,
  background: Color(0xFF0A0A0A),
  tabBarBackground: Color(0xFF050505),
  statusBarBackground: Color(0xFF000000),
  promptBackground: Color(0xFF141414),
  blockBackground: Color(0xFF161616),
  blockBorder: Color(0xFF2A2A2A),
  blockHeaderFg: Color(0xFFB8B8B8),
  exitSuccessFg: Color(0xFF7FE05F),
  exitFailureFg: Color(0xFFFF5F87),
  statusChipBg: Color(0xFF1E1E1E),
  statusCwdFg: Color(0xFF5FD4FF),
  statusGitFg: Color(0xFFD787FF),
  statusShellFg: Color(0xFF7FE05F),
  dimForeground: Color(0xFF6A6A6A),
  foreground: Color(0xFFE8E8E8),
  cursor: Color(0xFF5FD4FF),
  selectionColor: Color(0xFF2E3A4A),
  searchHitBackground: Color(0xFFFFD75F),
  searchHitBackgroundCurrent: Color(0xFFFF875F),
  searchHitForeground: Color(0xFF0A0A0A),
  ansiBlack: Color(0xFF0A0A0A),
  ansiRed: Color(0xFFFF5F87),
  ansiGreen: Color(0xFF7FE05F),
  ansiYellow: Color(0xFFFFD75F),
  ansiBlue: Color(0xFF5F9FFF),
  ansiMagenta: Color(0xFFD787FF),
  ansiCyan: Color(0xFF5FD4FF),
  ansiWhite: Color(0xFFB8B8B8),
  ansiBrightBlack: Color(0xFF6A6A6A),
  ansiBrightRed: Color(0xFFFF87A5),
  ansiBrightGreen: Color(0xFFA5F088),
  ansiBrightYellow: Color(0xFFFFE488),
  ansiBrightBlue: Color(0xFF88B8FF),
  ansiBrightMagenta: Color(0xFFE5A8FF),
  ansiBrightCyan: Color(0xFF88E0FF),
  ansiBrightWhite: Color(0xFFFFFFFF),
);
