import 'dart:ui';

import '../bolan_theme.dart';

const midnightCoveTheme = BolonTheme(
  name: 'midnight-cove',
  displayName: 'Midnight Cove',
  brightness: Brightness.dark,
  isBuiltIn: true,
  background: Color(0xFF0D1F2D),
  tabBarBackground: Color(0xFF0A0A15),
  statusBarBackground: Color(0xFF050F17),
  promptBackground: Color(0xFF12293A),
  blockBackground: Color(0xFF142B3D),
  blockBorder: Color(0xFF1F3F56),
  blockHeaderFg: Color(0xFFA8C5D8),
  exitSuccessFg: Color(0xFF6ED9B0),
  exitFailureFg: Color(0xFFFF7A85),
  statusChipBg: Color(0xFF1A3244),
  statusCwdFg: Color(0xFF7DD3FC),
  statusGitFg: Color(0xFFA8B5E6),
  statusShellFg: Color(0xFF6ED9B0),
  dimForeground: Color(0xFF5A7A8F),
  foreground: Color(0xFFD8E8F0),
  cursor: Color(0xFF7DD3FC),
  selectionColor: Color(0xFF2E5A78),
  searchHitBackground: Color(0xFFFFC857),
  searchHitBackgroundCurrent: Color(0xFFFF9E3B),
  searchHitForeground: Color(0xFF0D1F2D),
  ansiBlack: Color(0xFF0D1F2D),
  ansiRed: Color(0xFFFF7A85),
  ansiGreen: Color(0xFF6ED9B0),
  ansiYellow: Color(0xFFE8C97A),
  ansiBlue: Color(0xFF7DB8FF),
  ansiMagenta: Color(0xFFC4A7E8),
  ansiCyan: Color(0xFF7DD3FC),
  ansiWhite: Color(0xFFC8D5E0),
  ansiBrightBlack: Color(0xFF5A7A8F),
  ansiBrightRed: Color(0xFFFFA0A8),
  ansiBrightGreen: Color(0xFF95EDC8),
  ansiBrightYellow: Color(0xFFF5DCA0),
  ansiBrightBlue: Color(0xFFA8D0FF),
  ansiBrightMagenta: Color(0xFFDDC5F2),
  ansiBrightCyan: Color(0xFFB0E5FF),
  ansiBrightWhite: Color(0xFFEAF2F8),
);
